language: node_js
sudo: required
before_script:
- npm install -g bower polymer-cli@next
- polymer install --variants
- sudo mv /usr/bin/google-chrome /usr/bin/google-chrome-old
- sudo mv /usr/bin/google-chrome-stable /usr/bin/google-chrome
node_js: stable
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
script:
- xvfb-run polymer test
dist: trusty
global_env: 
group: stable
os: linux

