language: node_js
node_js: stable
dist: trusty
sudo: required
addons:
  firefox: latest
  sauce_connect: true
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install -g bower polylint web-component-tester
- bower install
- polylint
script:
- xvfb-run wct
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct -s 'default'; fi
env:
  global:
  - secure: NQCq2PnVtdIe51gya/IxMliTxbP3eUrbahZ9V+vvq2I9lpI3ya14tTQBWF0HzVgPK+ydustQK9V6NzLGtsLjtLGmQUgWav6jwPnrClHVvs/giXDtT7QStF/62hEzOYGGyZE0XuDgLHPR31dzLHV/p+AkGK8yef/hEmld5TV/EK4v6Dprh+fuMJSX/3PTR4E3E+1nLdEsnQyWzS7s+J2ZNhjXqtHrPpdwpM/X5BKEMgVbe3qfh3ffjrqKD/XcTkhLdeqZ5YKVXtXjW6UhObrpMFl84RR3APIUuFwseXQKHVqoN9XuVuZxT7q8cXbwx+zrK0PXyWuvhsqcK2WnUbgCh7TZr2iikHcVNHUiUJA+0K6yKvh6UGnHL67cO2TnPRXvEsQzaa3rokTMvFQbngzRG+B4jb24sSCh+8tyNXutRY2PEVB+FpB+XqmROYGw4wBGw6dPRPL1fAvbHw5CkK8z36FVHWE4TjUogOCSvDW1Pvv6wQ0cA310mkaNE1Y6u0Zs9Ke1rDJZddirPQWHJ1H31A7MA7Pswk5Q9LUZZRiNmDgApeWviReFyRWcEAx2c4V6d8882tVHZ3bzeXidJMYymek8Wh2fD8q/8hyOKmCyRqkXBurv9eOQb678HTq7OmATp02XdFxep4z26FghTKgrdUu2HNBJxceco+/GzLa2jdk=
  - secure: 4D7iTg20PNKSLTE6f8bKJfZ05HCn1Qt1RWQ9jh6kp8/RhVQxJcTkC4kS2PfoVLbElOskkUFY0KyQSzn6R2ZZj1b+QXtw9ZLZz81SriLGiSJr3+UNiZomzFGNzFYO7s8gB0uNFN28ouEku/aqPlV4CalGjtBv2XsZb3kw+7xH0PAjyANZyyjAMfgdJJaNGjGgqDTY6iGWTNPDMfH+zlgpQ8/vEC3uubfuRpGo4vmDr3ouazkaAI7l1rbLtkq7wVyMrknqtgsTSAgUr9IovgyveyJR0TZDiAlg9MVn53hO8EGpk1/fjt64DIz60hYcZkaK3S2ybi6SiCPIWAKlJvlM3Uyhrg6emHeRpaEcDbm9h9TfTp+fgVxwdja7fT/XsYY5lOhuBXhKjXzlNByNoKxl2Hmz16OpM3O1RUQmp4SOFnf893Gr6seonDeNxbXdv3KYxm7x/GWgeCl+vuk6kMb6WnlVHcuXofFgURnZzds6kRPZI9nZ61pGvSxd98WvEKfPyrSCVMTWjPI+NT/TvW+TAdW3cORCnCn9GxabAV2yv/bD5mc20KSQKGLWN/NfaZ16aYIC1mDKrls5UFEneeQbcFYOXFNlNfzymBC8GuYEIupl7uxHJVZYIoFLr3HJSeLvEDro3uAqBpsSUQD6oY0euXZUQDCs/dM4F0slZLtdndg=
