language: node_js
sudo: required
before_script:
- npm install -g bower polymer-cli@next
- polymer install --variants
- sudo mv /usr/bin/google-chrome /usr/bin/google-chrome-old
- sudo mv /usr/bin/google-chrome-stable /usr/bin/google-chrome
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start
- rackup  # start a Web server
- sleep 3 # give Web server some time to bind to sockets, etc
node_js: stable
addons:
  sauce_connect:
    username: "forando"
    access_key: "99bc8913-3226-4d9a-b4e1-4b9eb344f986"
script:
#- xvfb-run polymer test --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test; fi
dist: trusty
global_env: 
group: stable
os: linux

